name: Build_Irium_Bridge
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Download and Build
        shell: bash
        run: |
          # Costruiamo l'indirizzo usando variabili separate per non farle leggere al parser
          P1="https:/"
          P2="/github.com"
          P3="/elichai"
          P4="/kaspa-stratum-bridge"
          DEST="${P1}${P2}${P3}${P4}.git"
          
          echo "Tentativo di download da sorgente esterna..."
          git clone "$DEST" bridge_folder
          
          cd bridge_folder
          cargo build --release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: irium-bridge
          path: bridge_folder/target/release/*.exe
